classDiagram
    %% grepple:complete-package github.com/greppleai/grepple/rulespec
    %% grepple:package-default github.com/greppleai/grepple/rulespec
    %% grepple:language-default go
    %% grepple:exact-default
    class Engine {
        +Engine(api.Rule): string
    }
    <<function>> Engine
    %% grepple:file Engine rulespec/rule.go
    note for Engine "defined: rulespec/rule.go:20-25"
    class Normalize {
        +Normalize(api.Rule): tuple~api.Rule&#44;error~
    }
    <<function>> Normalize
    %% grepple:file Normalize rulespec/rule.go
    note for Normalize "defined: rulespec/rule.go:28-54"
