// Package metrics analyzes externally generated, privacy-safe agent utility journals.
package metrics

import (
	"bytes"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/alexflint/go-arg"
	cliruntime "github.com/greppleai/grepple/internal/cliruntime"
	agentmetrics "github.com/greppleai/grepple/internal/metrics"
)

// defaultTextOutputBytes keeps human-readable reports below common agent tool-result limits.
const defaultTextOutputBytes = 16 * 1024

const metricsHelp = `Analyze externally generated, privacy-safe agent utility JSONL.

Usage:
  grepple metrics report --input PATH [OPTIONS]
  grepple metrics compare --baseline REPORT.json --target REPORT.json [OPTIONS]

Report options:
  --input PATH          journal JSONL file or directory (required; repeatable)
  --format FORMAT       text, json, or csv

Compare options:
  --baseline PATH       baseline JSON report generated by metrics report
  --target PATH         target JSON report generated by metrics report
  --format FORMAT       text, json, or csv

Report reads only explicit --input paths; compare reads only the two explicit JSON reports.
Grepple does not collect, write, or discover journals.
Journals contain normalized opaque identifiers, counts, timestamps, and outcomes.
They never contain prompts, responses, source, tool output, raw queries, raw commands, command arguments, or content-bearing paths.
`

// ReportArgs selects explicit journal inputs for one metrics report.
type ReportArgs struct {
	Inputs []string `arg:"--input,separate" placeholder:"PATH" help:"journal JSONL file or directory (required; repeatable)"`
	Format string   `arg:"--format" default:"text" placeholder:"FORMAT" help:"text, json, or csv"`
}

// CompareArgs selects two generated JSON reports for comparison.
type CompareArgs struct {
	Baseline string `arg:"--baseline" placeholder:"PATH" help:"baseline JSON report generated by metrics report"`
	Target   string `arg:"--target" placeholder:"PATH" help:"target JSON report generated by metrics report"`
	Format   string `arg:"--format" default:"text" placeholder:"FORMAT" help:"text, json, or csv"`
}

// Args contains metrics command subcommands.
type Args struct {
	Report  *ReportArgs  `arg:"subcommand:report" help:"summarize explicit agent utility journal JSONL inputs"`
	Compare *CompareArgs `arg:"subcommand:compare" help:"compare two JSON reports generated by metrics report"`
}

// Description explains the metrics evidence contract in generated help.
func (Args) Description() string {
	return "Analyze externally generated, privacy-safe agent utility JSONL.\n" +
		"Report reads only explicit --input paths; compare reads only the two explicit JSON reports.\n" +
		"Grepple does not collect, write, or discover journals. Journals never contain prompts, responses, source, tool output, raw queries, raw commands, command arguments, or content-bearing paths."
}

// command owns one metrics command invocation.
type command struct{ context cliruntime.Context }

// New constructs the metrics command.
func New(context cliruntime.Context) cliruntime.Command { return &command{context: context} }

// Run parses metrics arguments and executes the selected subcommand.
func (command *command) Run(args []string) error {
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		return cliruntime.NewOutput(command.context.Stdout()).WriteString(metricsHelp)
	}
	values, help, err := parseMetricsArgs(args)
	if err != nil {
		return err
	}
	if help {
		return cliruntime.NewOutput(command.context.Stdout()).WriteString(metricsHelp)
	}
	return Execute(command.context, values)
}

func parseMetricsArgs(args []string) (*Args, bool, error) {
	switch args[0] {
	case "report", "compare":
	default:
		return nil, false, fmt.Errorf("unknown metrics command %q", args[0])
	}
	values := &Args{}
	parser, err := arg.NewParser(arg.Config{Program: "grepple metrics"}, values)
	if err != nil {
		return nil, false, err
	}
	if err := parser.Parse(args); err != nil {
		if errors.Is(err, arg.ErrHelp) {
			return values, true, nil
		}
		return nil, false, err
	}
	return values, false, nil
}

// Execute runs an application-parsed metrics command.
func Execute(application cliruntime.Context, values *Args) error {
	stdout := application.Stdout()
	var err error
	switch {
	case values != nil && values.Report != nil:
		err = executeReport(stdout, values.Report)
	case values != nil && values.Compare != nil:
		err = executeCompare(stdout, values.Compare)
	default:
		return cliruntime.NewOutput(stdout).WriteString(metricsHelp)
	}
	if errors.Is(err, cliruntime.ErrOutputTruncated) {
		return nil
	}
	return err
}

func validateMetricsFormat(format string) error {
	if format != "text" && format != "json" && format != "csv" {
		return fmt.Errorf("--format must be text, json, or csv")
	}
	return nil
}

func executeReport(stdout io.Writer, values *ReportArgs) error {
	if err := validateMetricsFormat(values.Format); err != nil {
		return err
	}
	if len(values.Inputs) == 0 {
		return fmt.Errorf("metrics report requires --input")
	}
	runs, err := loadMetricRuns(values.Inputs)
	if err != nil {
		return err
	}
	report := agentmetrics.BuildReport(runs)
	if values.Format != "text" {
		return exportMetrics(stdout, report, values.Format)
	}
	return writeMetricsReport(stdout, report)
}

func executeCompare(stdout io.Writer, values *CompareArgs) error {
	if err := validateMetricsFormat(values.Format); err != nil {
		return err
	}
	if values.Baseline == "" || values.Target == "" {
		return fmt.Errorf("metrics compare requires --baseline and --target")
	}
	baseline, err := agentmetrics.ReadReport(values.Baseline)
	if err != nil {
		return fmt.Errorf("baseline report: %w", err)
	}
	target, err := agentmetrics.ReadReport(values.Target)
	if err != nil {
		return fmt.Errorf("target report: %w", err)
	}
	comparison, err := agentmetrics.BuildComparison(baseline, target)
	if err != nil {
		return err
	}
	return outputMetricsComparison(stdout, comparison, values.Format)
}

func loadMetricRuns(inputs []string) ([]agentmetrics.Run, error) {
	paths, err := agentmetrics.DiscoverJournals(inputs)
	if err != nil {
		return nil, err
	}
	var result []agentmetrics.Run
	for _, path := range paths {
		runs, err := agentmetrics.AnalyzeFile(path)
		if err != nil {
			return nil, err
		}
		result = append(result, runs...)
	}
	return result, nil
}

func writeMetricsReport(stdout io.Writer, report agentmetrics.Report) error {
	var output strings.Builder
	fmt.Fprintln(&output, "Agent utility metrics (grouped by agent)")
	fmt.Fprintf(&output, "runs: %d  groups: %d\n\n", len(report.Runs), len(report.Groups))
	fmt.Fprintln(&output, "AGENT\tN\tSUCCESS\tTOKENS p50/p90\tCOST p50/p90\tTIME-ms p50/p90")
	for _, group := range report.Groups {
		writeMetricsGroup(&output, group)
	}
	for _, comparison := range report.Comparisons {
		writeMetricsReportComparison(&output, comparison)
	}
	return cliruntime.NewBoundedOutput(stdout, defaultTextOutputBytes).WriteString(output.String())
}

func writeMetricsGroup(output *strings.Builder, group agentmetrics.Group) {
	success := "unknown"
	if group.SuccessRate != nil {
		success = fmt.Sprintf("%.1f%% (%d/%d)", *group.SuccessRate*100, group.Successful, group.OutcomeSampleSize)
	}
	tokens := "unknown"
	cost := "unknown"
	if group.UsageSampleSize > 0 {
		tokens = fmt.Sprintf("%.0f/%.0f", group.Tokens.P50, group.Tokens.P90)
		cost = fmt.Sprintf("%.4f/%.4f", group.Cost.P50, group.Cost.P90)
	}
	fmt.Fprintf(output, "%s\t%d\t%s\t%s\t%s\t%.0f/%.0f\n", group.Name, group.SampleSize, success, tokens, cost, group.ElapsedMS.P50, group.ElapsedMS.P90)
	perSuccess := make([]string, 0, 3)
	if group.TokensPerSuccessfulTask != nil {
		perSuccess = append(perSuccess, fmt.Sprintf("tokens %.0f", *group.TokensPerSuccessfulTask), fmt.Sprintf("cost %.4f", *group.CostPerSuccessfulTask))
	}
	if group.TimePerSuccessfulTask != nil {
		perSuccess = append(perSuccess, fmt.Sprintf("time %.0fms", *group.TimePerSuccessfulTask))
	}
	if len(perSuccess) > 0 {
		fmt.Fprintf(output, "  per successful task: %s\n", strings.Join(perSuccess, ", "))
	}
}

func writeMetricsReportComparison(output *strings.Builder, comparison agentmetrics.Comparison) {
	fmt.Fprintf(output, "\nDescriptive deltas %s - %s (absolute, percent):", comparison.Target, comparison.Baseline)
	for _, metric := range []string{"tokensMedian", "costMedian", "elapsedMsMedian", "successRate", "tokensPerSuccessfulTask", "costPerSuccessfulTask", "timePerSuccessfulTask"} {
		if delta, ok := comparison.Metrics[metric]; ok {
			fmt.Fprintf(output, " %s %s;", metric, formatMetricDelta(delta))
		}
	}
	fmt.Fprintln(output, " no significance claim.")
}

func formatMetricDelta(delta agentmetrics.Delta) string {
	percent := "n/a"
	if delta.Percent != nil {
		percent = fmt.Sprintf("%+.1f%%", *delta.Percent)
	}
	return fmt.Sprintf("%+.4g (%s)", delta.Absolute, percent)
}

func exportMetrics(stdout io.Writer, report agentmetrics.Report, format string) error {
	if format == "json" {
		return cliruntime.NewOutput(stdout).WriteJSON(report)
	}
	var output bytes.Buffer
	writer := csv.NewWriter(&output)
	header := []string{"run_id", "agent", "observed_grepple_use", "complete", "outcome", "turns", "tool_calls", "grepple_calls", "tokens", "cost", "elapsed_ms", "files_inspected", "files_edited", "test_fix_cycles"}
	if err := writer.Write(header); err != nil {
		return err
	}
	for _, run := range report.Runs {
		elapsed := run.EndedAt.Sub(run.StartedAt).Milliseconds()
		turns := strconv.Itoa(run.Turns)
		if metricRunMissing(run, "agent_turns") {
			turns = ""
		}
		tokens := strconv.FormatInt(run.Usage.TotalTokens, 10)
		cost := strconv.FormatFloat(run.Usage.Cost, 'f', 6, 64)
		if metricRunMissing(run, "assistant_usage") {
			tokens = ""
			cost = ""
		}
		row := []string{run.RunID, run.Agent, strconv.FormatBool(run.ObservedGreppleUse), strconv.FormatBool(run.Complete), run.Outcome.Status, turns, strconv.Itoa(run.Tools.Total), strconv.Itoa(run.Tools.Grepple), tokens, cost, strconv.FormatInt(elapsed, 10), strconv.Itoa(run.DistinctInspectedFiles), strconv.Itoa(run.DistinctEditedFiles), strconv.Itoa(run.TestFixCycles)}
		if err := writer.Write(row); err != nil {
			return err
		}
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		return err
	}
	return cliruntime.NewOutput(stdout).WriteString(output.String())
}

func metricRunMissing(run agentmetrics.Run, evidence string) bool {
	for _, missing := range run.Missing {
		if missing == evidence {
			return true
		}
	}
	return false
}

func outputMetricsComparison(stdout io.Writer, report agentmetrics.ComparisonReport, format string) error {
	if format == "json" {
		return cliruntime.NewOutput(stdout).WriteJSON(report)
	}
	metricNames := make([]string, 0, len(report.Delta.Metrics))
	for name := range report.Delta.Metrics {
		metricNames = append(metricNames, name)
	}
	sort.Strings(metricNames)
	if format == "csv" {
		return writeMetricsComparisonCSV(stdout, report, metricNames)
	}
	var output strings.Builder
	fmt.Fprintf(&output, "Agent utility comparison: %s -> %s\n", report.Baseline.Name, report.Target.Name)
	for _, name := range metricNames {
		fmt.Fprintf(&output, "%s\t%s\n", name, formatMetricDelta(report.Delta.Metrics[name]))
	}
	fmt.Fprintln(&output, "Descriptive deltas only; no significance claim.")
	return cliruntime.NewBoundedOutput(stdout, defaultTextOutputBytes).WriteString(output.String())
}

func writeMetricsComparisonCSV(stdout io.Writer, report agentmetrics.ComparisonReport, metricNames []string) error {
	var output bytes.Buffer
	writer := csv.NewWriter(&output)
	if err := writer.Write([]string{"metric", "baseline", "target", "absolute", "percent"}); err != nil {
		return err
	}
	for _, name := range metricNames {
		delta := report.Delta.Metrics[name]
		percent := ""
		if delta.Percent != nil {
			percent = strconv.FormatFloat(*delta.Percent, 'g', -1, 64)
		}
		row := []string{name, strconv.FormatFloat(comparisonMetricValue(report.Baseline, name), 'g', -1, 64), strconv.FormatFloat(comparisonMetricValue(report.Target, name), 'g', -1, 64), strconv.FormatFloat(delta.Absolute, 'g', -1, 64), percent}
		if err := writer.Write(row); err != nil {
			return err
		}
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		return err
	}
	return cliruntime.NewOutput(stdout).WriteString(output.String())
}

func comparisonMetricValue(group agentmetrics.Group, name string) float64 {
	switch name {
	case "tokensMean":
		return group.Tokens.Mean
	case "tokensMedian":
		return group.Tokens.Median
	case "tokensP90":
		return group.Tokens.P90
	case "costMean":
		return group.Cost.Mean
	case "costMedian":
		return group.Cost.Median
	case "costP90":
		return group.Cost.P90
	case "elapsedMsMean":
		return group.ElapsedMS.Mean
	case "elapsedMsMedian":
		return group.ElapsedMS.Median
	case "elapsedMsP90":
		return group.ElapsedMS.P90
	case "successRate":
		return *group.SuccessRate
	case "tokensPerSuccessfulTask":
		return *group.TokensPerSuccessfulTask
	case "costPerSuccessfulTask":
		return *group.CostPerSuccessfulTask
	case "timePerSuccessfulTask":
		return *group.TimePerSuccessfulTask
	default:
		return 0
	}
}
