classDiagram
    %% grepple:complete-package github.com/greppleai/grepple/search
    %% grepple:package-default github.com/greppleai/grepple/search
    %% grepple:language-default go
    %% grepple:exact-default
    class FileMatch {
        +Content: string
        +DisplayPath: string
        +File: string
        +Language: string
        +MatchLines: map[int]bool
        +MatchRanges: map[int]parser.StructuralLineRange
        +OmittedRelatedCallees: int
        +OmittedRelatedCallers: int
        +Related: []RelatedPoint
        +Segments: []parser.Segment
        +SegmentsReady: bool
    }
    <<struct>> FileMatch
    %% grepple:file FileMatch search/model.go
    note for FileMatch "defined: search/model.go:55-63; Content@search/model.go:56; DisplayPath@search/model.go:56; File@search/model.go:56; Language@search/model.go:56; MatchLines@search/model.go:57; MatchRanges@search/model.go:58; OmittedRelatedCallees@search/model.go:61; OmittedRelatedCallers@search/model.go:61; Related@search/model.go:60; Segments@search/model.go:59; SegmentsReady@search/model.go:62"
    class NavigationCallDelta {
        +After: *parser.NavigationCall
        +Before: *parser.NavigationCall
    }
    <<struct>> NavigationCallDelta
    %% grepple:file NavigationCallDelta search/navigation_diff.go
    %% grepple:struct-tag NavigationCallDelta After "json:\"after,omitempty\""
    %% grepple:struct-tag NavigationCallDelta Before "json:\"before,omitempty\""
    note for NavigationCallDelta "defined: search/navigation_diff.go:21-24; After@search/navigation_diff.go:23; Before@search/navigation_diff.go:22"
    class NavigationDeclarationDelta {
        +After: *parser.NavigationDeclaration
        +Before: *parser.NavigationDeclaration
    }
    <<struct>> NavigationDeclarationDelta
    %% grepple:file NavigationDeclarationDelta search/navigation_diff.go
    %% grepple:struct-tag NavigationDeclarationDelta After "json:\"after,omitempty\""
    %% grepple:struct-tag NavigationDeclarationDelta Before "json:\"before,omitempty\""
    note for NavigationDeclarationDelta "defined: search/navigation_diff.go:15-18; After@search/navigation_diff.go:17; Before@search/navigation_diff.go:16"
    class NavigationGraphDiff {
        +AddedCalls: []parser.NavigationCall
        +AddedDeclarations: []parser.NavigationDeclaration
        +ChangedCalls: []NavigationCallDelta
        +ChangedDeclarations: []NavigationDeclarationDelta
        +MovedDeclarations: []NavigationDeclarationDelta
        +RemovedCalls: []parser.NavigationCall
        +RemovedDeclarations: []parser.NavigationDeclaration
        +Schema: string
    }
    <<struct>> NavigationGraphDiff
    %% grepple:file NavigationGraphDiff search/navigation_diff.go
    %% grepple:struct-tag NavigationGraphDiff AddedCalls "json:\"addedCalls,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff AddedDeclarations "json:\"addedDeclarations,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff ChangedCalls "json:\"changedCalls,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff ChangedDeclarations "json:\"changedDeclarations,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff MovedDeclarations "json:\"movedDeclarations,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff RemovedCalls "json:\"removedCalls,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff RemovedDeclarations "json:\"removedDeclarations,omitempty\""
    %% grepple:struct-tag NavigationGraphDiff Schema "json:\"schema\""
    note for NavigationGraphDiff "defined: search/navigation_diff.go:27-36; AddedCalls@search/navigation_diff.go:33; AddedDeclarations@search/navigation_diff.go:29; ChangedCalls@search/navigation_diff.go:35; ChangedDeclarations@search/navigation_diff.go:32; MovedDeclarations@search/navigation_diff.go:31; RemovedCalls@search/navigation_diff.go:34; RemovedDeclarations@search/navigation_diff.go:30; Schema@search/navigation_diff.go:28"
    class NavigationGraphFilter {
        +Confidences: []string
        +Languages: []string
        +Visibilities: []string
    }
    <<struct>> NavigationGraphFilter
    %% grepple:file NavigationGraphFilter search/navigation_filter.go
    note for NavigationGraphFilter "defined: search/navigation_filter.go:12-16; Confidences@search/navigation_filter.go:14; Languages@search/navigation_filter.go:13; Visibilities@search/navigation_filter.go:15"
    class NavigationQueryDirection["NavigationQueryDirection = string"]
    <<type>> NavigationQueryDirection
    %% grepple:underlying NavigationQueryDirection string
    %% grepple:file NavigationQueryDirection search/navigation_query.go
    note for NavigationQueryDirection "defined: search/navigation_query.go:10"
    class Params {
        +AfterContext: int
        +At: string
        +BeforeContext: int
        +Context: int
        +CountByRepo: bool
        +EnclosingRanges: bool
        +ExcludeRepo: []string
        +Files: bool
        +FollowRelated: int
        +Globs: []string
        +IgnoreCase: bool
        +InvertMatch: bool
        +Limit: int
        +LineRanges: bool
        +MaxFiles: int
        +MaxSegments: int
        +Query: string
        +Regex: bool
        +Related: bool
        +Repo: []string
        +Root: string
        +Skip: int
        +SkipSegments: bool
    }
    <<struct>> Params
    %% grepple:file Params search/model.go
    %% grepple:struct-tag Params AfterContext "json:\"afterContext,omitempty\""
    %% grepple:struct-tag Params At "json:\"-\""
    %% grepple:struct-tag Params BeforeContext "json:\"beforeContext,omitempty\""
    %% grepple:struct-tag Params Context "json:\"context,omitempty\""
    %% grepple:struct-tag Params CountByRepo "json:\"-\""
    %% grepple:struct-tag Params EnclosingRanges "json:\"enclosingLineRanges,omitempty\""
    %% grepple:struct-tag Params ExcludeRepo "json:\"excludeRepo,omitempty\""
    %% grepple:struct-tag Params Files "json:\"files,omitempty\""
    %% grepple:struct-tag Params FollowRelated "json:\"followRelated,omitempty\""
    %% grepple:struct-tag Params Globs "json:\"globs\""
    %% grepple:struct-tag Params IgnoreCase "json:\"ignoreCase\""
    %% grepple:struct-tag Params InvertMatch "json:\"invertMatch,omitempty\""
    %% grepple:struct-tag Params Limit "json:\"limit,omitempty\""
    %% grepple:struct-tag Params LineRanges "json:\"matchLineRanges,omitempty\""
    %% grepple:struct-tag Params MaxFiles "json:\"maxFiles,omitempty\""
    %% grepple:struct-tag Params MaxSegments "json:\"maxSegments\""
    %% grepple:struct-tag Params Query "json:\"query\""
    %% grepple:struct-tag Params Regex "json:\"regex\""
    %% grepple:struct-tag Params Related "json:\"related,omitempty\""
    %% grepple:struct-tag Params Repo "json:\"repo,omitempty\""
    %% grepple:struct-tag Params Root "json:\"-\""
    %% grepple:struct-tag Params Skip "json:\"skip,omitempty\""
    %% grepple:struct-tag Params SkipSegments "json:\"-\""
    note for Params "defined: search/model.go:11-35; AfterContext@search/model.go:26; At@search/model.go:32; BeforeContext@search/model.go:25; Context@search/model.go:24; CountByRepo@search/model.go:34; EnclosingRanges@search/model.go:29; ExcludeRepo@search/model.go:22; Files@search/model.go:23; FollowRelated@search/model.go:31; Globs@search/model.go:13; IgnoreCase@search/model.go:15; InvertMatch@search/model.go:16; Limit@search/model.go:20; LineRanges@search/model.go:28; MaxFiles@search/model.go:17; MaxSegments@search/model.go:18; Query@search/model.go:12; Regex@search/model.go:14; Related@search/model.go:30; Repo@search/model.go:21; Root@search/model.go:33; Skip@search/model.go:19; SkipSegments@search/model.go:27"
    class RelatedPoint {
        +CallLine: int
        +Confidence: string
        +Direction: string
        +Distance: int
        +End: int
        +File: string
        +Kind: string
        +Name: string
        +Path: string
        +Preview: *RelatedPreview
        +Start: int
    }
    <<struct>> RelatedPoint
    %% grepple:file RelatedPoint search/model.go
    note for RelatedPoint "defined: search/model.go:47-51; CallLine@search/model.go:49; Confidence@search/model.go:48; Direction@search/model.go:48; Distance@search/model.go:49; End@search/model.go:49; File@search/model.go:48; Kind@search/model.go:48; Name@search/model.go:48; Path@search/model.go:48; Preview@search/model.go:50; Start@search/model.go:49"
    class RelatedPreview {
        +Content: string
        +End: int
        +OmittedCallees: int
        +OmittedCallers: int
        +Related: []RelatedPoint
        +Start: int
    }
    <<struct>> RelatedPreview
    %% grepple:file RelatedPreview search/model.go
    note for RelatedPreview "defined: search/model.go:39-44; Content@search/model.go:40; End@search/model.go:41; OmittedCallees@search/model.go:43; OmittedCallers@search/model.go:43; Related@search/model.go:42; Start@search/model.go:41"
    class RepoFilter {
        +Allow(string): bool
        -exclude: []repoPattern
        -include: []repoPattern
    }
    <<struct>> RepoFilter
    %% grepple:file RepoFilter search/search_engine.go
    note for RepoFilter "defined: search/search_engine.go:129-132; Allow@search/search_engine.go:144-166; exclude@search/search_engine.go:131; include@search/search_engine.go:130"
    class ResponsibilityBoundaryCandidate {
        +CallableCoUsage: []ResponsibilityPattern
        +Callables: []string
        +ConsumerDetails: []ResponsibilityConsumer
        +Consumers: ResponsibilityBreadth
        +ExternalCallableSurface: ResponsibilitySurface
        +Language: string
        +MemberCallCombinations: []ResponsibilityPattern
        +OrderedSequences: []ResponsibilityPattern
        +OwnerFile: string
        +UnresolvedCalls: int
    }
    <<struct>> ResponsibilityBoundaryCandidate
    %% grepple:file ResponsibilityBoundaryCandidate search/responsibility_boundaries.go
    %% grepple:struct-tag ResponsibilityBoundaryCandidate CallableCoUsage "json:\"callableCoUsage\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate Callables "json:\"callables\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate ConsumerDetails "json:\"consumerDetails\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate Consumers "json:\"consumers\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate ExternalCallableSurface "json:\"externalCallableSurface\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate Language "json:\"language\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate MemberCallCombinations "json:\"memberCallCombinations\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate OrderedSequences "json:\"orderedSequences\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate OwnerFile "json:\"ownerFile\""
    %% grepple:struct-tag ResponsibilityBoundaryCandidate UnresolvedCalls "json:\"unresolvedCalls\""
    note for ResponsibilityBoundaryCandidate "defined: search/responsibility_boundaries.go:12-23; CallableCoUsage@search/responsibility_boundaries.go:19; Callables@search/responsibility_boundaries.go:18; ConsumerDetails@search/responsibility_boundaries.go:16; Consumers@search/responsibility_boundaries.go:15; ExternalCallableSurface@search/responsibility_boundaries.go:17; Language@search/responsibility_boundaries.go:14; MemberCallCombinations@search/responsibility_boundaries.go:21; OrderedSequences@search/responsibility_boundaries.go:20; OwnerFile@search/responsibility_boundaries.go:13; UnresolvedCalls@search/responsibility_boundaries.go:22"
    class ResponsibilityBreadth {
        +Files: int
        +Functions: int
        +Packages: int
    }
    <<struct>> ResponsibilityBreadth
    %% grepple:file ResponsibilityBreadth search/responsibilities.go
    %% grepple:struct-tag ResponsibilityBreadth Files "json:\"files\""
    %% grepple:struct-tag ResponsibilityBreadth Functions "json:\"functions\""
    %% grepple:struct-tag ResponsibilityBreadth Packages "json:\"packages\""
    note for ResponsibilityBreadth "defined: search/responsibilities.go:13-17; Files@search/responsibilities.go:15; Functions@search/responsibilities.go:14; Packages@search/responsibilities.go:16"
    class ResponsibilityConsumer {
        +ID: string
        +Line: int
        +Name: string
        +Package: string
        +Path: string
    }
    <<struct>> ResponsibilityConsumer
    %% grepple:file ResponsibilityConsumer search/responsibilities.go
    %% grepple:struct-tag ResponsibilityConsumer ID "json:\"id\""
    %% grepple:struct-tag ResponsibilityConsumer Line "json:\"line\""
    %% grepple:struct-tag ResponsibilityConsumer Name "json:\"name\""
    %% grepple:struct-tag ResponsibilityConsumer Package "json:\"package,omitempty\""
    %% grepple:struct-tag ResponsibilityConsumer Path "json:\"path\""
    note for ResponsibilityConsumer "defined: search/responsibilities.go:26-32; ID@search/responsibilities.go:27; Line@search/responsibilities.go:31; Name@search/responsibilities.go:28; Package@search/responsibilities.go:30; Path@search/responsibilities.go:29"
    class ResponsibilityPattern {
        +Consumers: []ResponsibilityConsumer
        +Files: int
        +Methods: []string
        +Occurrences: int
        +Packages: int
    }
    <<struct>> ResponsibilityPattern
    %% grepple:file ResponsibilityPattern search/responsibilities.go
    %% grepple:struct-tag ResponsibilityPattern Consumers "json:\"consumers\""
    %% grepple:struct-tag ResponsibilityPattern Files "json:\"files\""
    %% grepple:struct-tag ResponsibilityPattern Methods "json:\"methods\""
    %% grepple:struct-tag ResponsibilityPattern Occurrences "json:\"occurrences\""
    %% grepple:struct-tag ResponsibilityPattern Packages "json:\"packages\""
    note for ResponsibilityPattern "defined: search/responsibilities.go:35-41; Consumers@search/responsibilities.go:40; Files@search/responsibilities.go:38; Methods@search/responsibilities.go:36; Occurrences@search/responsibilities.go:37; Packages@search/responsibilities.go:39"
    class ResponsibilityReport {
        +ConsumerDetails: []ResponsibilityConsumer
        +Consumers: ResponsibilityBreadth
        +ExternalMethodSurface: ResponsibilitySurface
        +Languages: []string
        +MemberMethodCombinations: []ResponsibilityPattern
        +MethodCoUsage: []ResponsibilityPattern
        +Methods: []string
        +OrderedSequences: []ResponsibilityPattern
        +Schema: string
        +Type: string
        +UnresolvedCalls: int
    }
    <<struct>> ResponsibilityReport
    %% grepple:file ResponsibilityReport search/responsibilities.go
    %% grepple:struct-tag ResponsibilityReport ConsumerDetails "json:\"consumerDetails\""
    %% grepple:struct-tag ResponsibilityReport Consumers "json:\"consumers\""
    %% grepple:struct-tag ResponsibilityReport ExternalMethodSurface "json:\"externalMethodSurface\""
    %% grepple:struct-tag ResponsibilityReport Languages "json:\"languages\""
    %% grepple:struct-tag ResponsibilityReport MemberMethodCombinations "json:\"memberMethodCombinations\""
    %% grepple:struct-tag ResponsibilityReport MethodCoUsage "json:\"methodCoUsage\""
    %% grepple:struct-tag ResponsibilityReport Methods "json:\"methods\""
    %% grepple:struct-tag ResponsibilityReport OrderedSequences "json:\"orderedSequences\""
    %% grepple:struct-tag ResponsibilityReport Schema "json:\"schema\""
    %% grepple:struct-tag ResponsibilityReport Type "json:\"type\""
    %% grepple:struct-tag ResponsibilityReport UnresolvedCalls "json:\"unresolvedCalls\""
    note for ResponsibilityReport "defined: search/responsibilities.go:44-56; ConsumerDetails@search/responsibilities.go:49; Consumers@search/responsibilities.go:48; ExternalMethodSurface@search/responsibilities.go:50; Languages@search/responsibilities.go:47; MemberMethodCombinations@search/responsibilities.go:54; MethodCoUsage@search/responsibilities.go:52; Methods@search/responsibilities.go:51; OrderedSequences@search/responsibilities.go:53; Schema@search/responsibilities.go:45; Type@search/responsibilities.go:46; UnresolvedCalls@search/responsibilities.go:55"
    class ResponsibilitySurface {
        +Declared: int
        +External: int
    }
    <<struct>> ResponsibilitySurface
    %% grepple:file ResponsibilitySurface search/responsibilities.go
    %% grepple:struct-tag ResponsibilitySurface Declared "json:\"declared\""
    %% grepple:struct-tag ResponsibilitySurface External "json:\"external\""
    note for ResponsibilitySurface "defined: search/responsibilities.go:20-23; Declared@search/responsibilities.go:22; External@search/responsibilities.go:21"
    class candidateCollector {
        -add(string)
        -addPlainGlob(string): error
        -addRecursiveGlob(string): error
        -addSubtree(string): error
        -ctx: context.Context
        -cwd: string
        -files: []string
        -ignoreCache: gitignoreCache
        -root: string
        -seen: map[string]bool
    }
    <<struct>> candidateCollector
    %% grepple:file candidateCollector search/search_glob.go
    note for candidateCollector "defined: search/search_glob.go:146-152; add@search/search_glob.go:160-168; addPlainGlob@search/search_glob.go:191-220; addRecursiveGlob@search/search_glob.go:223-232; addSubtree@search/search_glob.go:172-187; ctx@search/search_glob.go:147; cwd@search/search_glob.go:148; files@search/search_glob.go:151; ignoreCache@search/search_glob.go:149; root@search/search_glob.go:148; seen@search/search_glob.go:150"
    class candidateScan {
        -relatedFiles([]string): []string
        -scanAll([]string): []FileMatch
        -scanWindowed([]string, int): []FileMatch
        -fromIndex: bool
        -m: func&#40;string&#41;bool
        -p: Params
        -repoFilter: *RepoFilter
    }
    <<struct>> candidateScan
    %% grepple:file candidateScan search/search_engine.go
    note for candidateScan "defined: search/search_engine.go:232-237; relatedFiles@search/search_engine.go:239-252; scanAll@search/search_engine.go:258-267; scanWindowed@search/search_engine.go:272-295; fromIndex@search/search_engine.go:236; m@search/search_engine.go:234; p@search/search_engine.go:233; repoFilter@search/search_engine.go:235"
    class candidateWalker {
        -walk(string, fs.DirEntry, error): error
        -walkDir(string, string): error
        -ctx: context.Context
        -files: []string
        -ignorePatterns: map[string][]string
        -root: string
    }
    <<struct>> candidateWalker
    %% grepple:file candidateWalker search/search_glob.go
    note for candidateWalker "defined: search/search_glob.go:394-399; walk@search/search_glob.go:404-425; walkDir@search/search_glob.go:429-439; ctx@search/search_glob.go:395; files@search/search_glob.go:398; ignorePatterns@search/search_glob.go:397; root@search/search_glob.go:396"
    class gitignoreCache["gitignoreCache = map&#91;string&#93;&#91;&#93;string"] {
        -patterns(string): []string
    }
    <<type>> gitignoreCache
    %% grepple:underlying gitignoreCache map[string][]string
    %% grepple:file gitignoreCache search/search_glob.go
    note for gitignoreCache "defined: search/search_glob.go:461; patterns@search/search_glob.go:463-471"
    class navigationCall {
        -callerID: string
        -display: string
        -factoryImport: string
        -file: string
        -id: string
        -importDirectory: string
        -importPath: string
        -importSourceFile: string
        -line: int
        -moduleKnown: bool
        -name: string
        -qualifier: string
        -receiverFactory: string
        -receiverType: string
        -resolvedName: string
    }
    <<struct>> navigationCall
    %% grepple:file navigationCall search/related.go
    note for navigationCall "defined: search/related.go:38-47; callerID@search/related.go:39; display@search/related.go:40; factoryImport@search/related.go:43; file@search/related.go:43; id@search/related.go:39; importDirectory@search/related.go:44; importPath@search/related.go:41; importSourceFile@search/related.go:44; line@search/related.go:46; moduleKnown@search/related.go:45; name@search/related.go:40; qualifier@search/related.go:41; receiverFactory@search/related.go:42; receiverType@search/related.go:42; resolvedName@search/related.go:40"
    class navigationCaller {
        -call: navigationCall
        -declaration: navigationDeclaration
    }
    <<struct>> navigationCaller
    %% grepple:file navigationCaller search/related.go
    note for navigationCaller "defined: search/related.go:33-36; call@search/related.go:35; declaration@search/related.go:34"
    class navigationCandidateResolution {
        -candidates: []navigationDeclaration
        -confidence: string
    }
    <<struct>> navigationCandidateResolution
    %% grepple:file navigationCandidateResolution search/related.go
    note for navigationCandidateResolution "defined: search/related.go:361-364; candidates@search/related.go:362; confidence@search/related.go:363"
    class navigationDeclaration {
        -container: string
        -file: string
        -id: string
        -language: string
        -matchStart: int
        -packageName: string
        -point: RelatedPoint
        -returnImportPath: string
        -returnType: string
        -terminal: string
    }
    <<struct>> navigationDeclaration
    %% grepple:file navigationDeclaration search/related.go
    note for navigationDeclaration "defined: search/related.go:20-31; container@search/related.go:23; file@search/related.go:28; id@search/related.go:21; language@search/related.go:27; matchStart@search/related.go:29; packageName@search/related.go:26; point@search/related.go:30; returnImportPath@search/related.go:25; returnType@search/related.go:24; terminal@search/related.go:22"
    class navigationIndex {
        -addCalls([]parser.NavigationCall, []navigationDeclaration, string, string)
        -addDeclarations([]parser.NavigationDeclaration, string, string, string): []navigationDeclaration
        -addFile(string, string)
        -indexNavigationCallers()
        -inferCallReturnReceiver(*navigationCall, string)
        -inferCallReturnReceivers()
        -navigationCallsByID(): map[string]navigationCall
        -navigationDeclarationsByID(): map[string]navigationDeclaration
        -resolveGraphCall(*parser.NavigationCall, map[string]navigationCall, map[string]navigationDeclaration)
        -resolveGraphCalls()
        -resolveReturnFactory(navigationCall, string): tuple~navigationDeclaration&#44;bool~
        -byFile: map[string][]navigationDeclaration
        -byLocation: map[string]navigationDeclaration
        -callers: map[string][]navigationCaller
        -calls: map[string][]navigationCall
        -contents: map[string]string
        -declarations: map[string][]navigationDeclaration
        -graph: parser.NavigationGraph
    }
    <<struct>> navigationIndex
    %% grepple:file navigationIndex search/related.go
    note for navigationIndex "defined: search/related.go:49-57; addCalls@search/related.go:224-242; addDeclarations@search/related.go:204-222; addFile@search/related.go:181-202; indexNavigationCallers@search/related.go:289-305; inferCallReturnReceiver@search/related.go:257-273; inferCallReturnReceivers@search/related.go:244-255; navigationCallsByID@search/related.go:141-149; navigationDeclarationsByID@search/related.go:131-139; resolveGraphCall@search/related.go:151-180; resolveGraphCalls@search/related.go:123-129; resolveReturnFactory@search/related.go:275-287; byFile@search/related.go:53; byLocation@search/related.go:54; callers@search/related.go:51; calls@search/related.go:52; contents@search/related.go:55; declarations@search/related.go:50; graph@search/related.go:56"
    class repoPattern {
        -match(string): bool
        -glob: string
        -re: *regexp.Regexp
    }
    <<struct>> repoPattern
    %% grepple:file repoPattern search/search_engine.go
    note for repoPattern "defined: search/search_engine.go:95-98; match@search/search_engine.go:108-113; glob@search/search_engine.go:96; re@search/search_engine.go:97"
    class responsibilityAnalyzer {
        -addResponsibilityCaller(string, []responsibilityInteraction, *responsibilityPatternGroups): tuple~ResponsibilityConsumer&#44;bool~
        -indexResponsibilityCalls([]parser.NavigationCall)
        -indexResponsibilityDeclarations([]parser.NavigationDeclaration)
        -indexResponsibilityMemberAccesses([]parser.NavigationMemberAccess)
        -indexResponsibilityTypeUsages([]parser.NavigationTypeUsage)
        -matchCall(parser.NavigationCall): tuple~string&#44;bool&#44;bool~
        -report(int): ResponsibilityReport
        -callsByCaller: map[string][]string
        -declarations: map[string]parser.NavigationDeclaration
        -interactionsByCaller: map[string][]responsibilityInteraction
        -languages: map[string]bool
        -methodIDs: map[string]bool
        -methods: map[string]bool
        -typeName: string
        -unresolvedCall: int
        -usageCallers: map[string]bool
    }
    <<struct>> responsibilityAnalyzer
    %% grepple:file responsibilityAnalyzer search/responsibilities.go
    note for responsibilityAnalyzer "defined: search/responsibilities.go:80-90; addResponsibilityCaller@search/responsibilities.go:203-224; indexResponsibilityCalls@search/responsibilities.go:115-130; indexResponsibilityDeclarations@search/responsibilities.go:104-113; indexResponsibilityMemberAccesses@search/responsibilities.go:132-142; indexResponsibilityTypeUsages@search/responsibilities.go:144-151; matchCall@search/responsibilities.go:153-173; report@search/responsibilities.go:175-194; callsByCaller@search/responsibilities.go:86; declarations@search/responsibilities.go:82; interactionsByCaller@search/responsibilities.go:87; languages@search/responsibilities.go:85; methodIDs@search/responsibilities.go:83; methods@search/responsibilities.go:84; typeName@search/responsibilities.go:81; unresolvedCall@search/responsibilities.go:89; usageCallers@search/responsibilities.go:88"
    class responsibilityInteraction {
        -label: string
    }
    <<struct>> responsibilityInteraction
    %% grepple:file responsibilityInteraction search/responsibilities.go
    note for responsibilityInteraction "defined: search/responsibilities.go:76-78; label@search/responsibilities.go:77"
    class responsibilityOwnerAnalysis {
        -called: map[string]bool
        -callers: map[string]parser.NavigationDeclaration
        -callsByCaller: map[string][]string
        -declared: int
        -interactions: map[string][]responsibilityInteraction
        -unresolvedCalls: int
    }
    <<struct>> responsibilityOwnerAnalysis
    %% grepple:file responsibilityOwnerAnalysis search/responsibility_boundaries.go
    note for responsibilityOwnerAnalysis "defined: search/responsibility_boundaries.go:30-37; called@search/responsibility_boundaries.go:34; callers@search/responsibility_boundaries.go:31; callsByCaller@search/responsibility_boundaries.go:32; declared@search/responsibility_boundaries.go:35; interactions@search/responsibility_boundaries.go:33; unresolvedCalls@search/responsibility_boundaries.go:36"
    class responsibilityOwnerKey {
        -language: string
        -path: string
    }
    <<struct>> responsibilityOwnerKey
    %% grepple:file responsibilityOwnerKey search/responsibility_boundaries.go
    note for responsibilityOwnerKey "defined: search/responsibility_boundaries.go:25-28; language@search/responsibility_boundaries.go:26; path@search/responsibility_boundaries.go:27"
    class responsibilityPatternGroup {
        -consumers: []ResponsibilityConsumer
        -methods: []string
    }
    <<struct>> responsibilityPatternGroup
    %% grepple:file responsibilityPatternGroup search/responsibilities.go
    note for responsibilityPatternGroup "defined: search/responsibilities.go:304-307; consumers@search/responsibilities.go:306; methods@search/responsibilities.go:305"
    class responsibilityPatternGroups {
        -combinations: map[string]*responsibilityPatternGroup
        -externalMethods: map[string]bool
        -methodSets: map[string]*responsibilityPatternGroup
        -sequences: map[string]*responsibilityPatternGroup
    }
    <<struct>> responsibilityPatternGroups
    %% grepple:file responsibilityPatternGroups search/responsibilities.go
    note for responsibilityPatternGroups "defined: search/responsibilities.go:196-201; combinations@search/responsibilities.go:200; externalMethods@search/responsibilities.go:197; methodSets@search/responsibilities.go:198; sequences@search/responsibilities.go:199"
    class responsibilityTypeCandidate {
        -language: string
        -typeName: string
    }
    <<struct>> responsibilityTypeCandidate
    %% grepple:file responsibilityTypeCandidate search/responsibility_boundaries.go
    note for responsibilityTypeCandidate "defined: search/responsibility_boundaries.go:169-172; language@search/responsibility_boundaries.go:171; typeName@search/responsibility_boundaries.go:170"
    class AggregateRepoCounts {
        +AggregateRepoCounts([]FileMatch): []api.RepoCount
    }
    <<function>> AggregateRepoCounts
    %% grepple:file AggregateRepoCounts search/search_engine.go
    note for AggregateRepoCounts "defined: search/search_engine.go:494-513"
    class AnalyzeDirectoryResponsibilities {
        +AnalyzeDirectoryResponsibilities(parser.NavigationGraph, int): tuple~[]ResponsibilityBoundaryCandidate&#44;error~
    }
    <<function>> AnalyzeDirectoryResponsibilities
    %% grepple:file AnalyzeDirectoryResponsibilities search/responsibility_boundaries.go
    note for AnalyzeDirectoryResponsibilities "defined: search/responsibility_boundaries.go:42-66"
    class AnalyzeResponsibilities {
        +AnalyzeResponsibilities(parser.NavigationGraph, string, int): tuple~ResponsibilityReport&#44;error~
    }
    <<function>> AnalyzeResponsibilities
    %% grepple:file AnalyzeResponsibilities search/responsibilities.go
    note for AnalyzeResponsibilities "defined: search/responsibilities.go:61-74"
    class At {
        +At(Params): tuple~*FileMatch&#44;error~
    }
    <<function>> At
    %% grepple:file At search/at.go
    note for At "defined: search/at.go:16-63"
    class BuildNavigationGraph {
        +BuildNavigationGraph([]string): parser.NavigationGraph
    }
    <<function>> BuildNavigationGraph
    %% grepple:file BuildNavigationGraph search/related.go
    note for BuildNavigationGraph "defined: search/related.go:119-121"
    class BuildResults {
        +BuildResults([]FileMatch, int, int, int, bool): []api.FileResult
    }
    <<function>> BuildResults
    %% grepple:file BuildResults search/result.go
    note for BuildResults "defined: search/result.go:74-87"
    class CollectFilesUnder {
        +CollectFilesUnder([]string, string): tuple~[]string&#44;error~
    }
    <<function>> CollectFilesUnder
    %% grepple:file CollectFilesUnder search/search_glob.go
    note for CollectFilesUnder "defined: search/search_glob.go:88-105"
    class Content {
        +Content(Params, string, []byte): tuple~*FileMatch&#44;error~
    }
    <<function>> Content
    %% grepple:file Content search/search_engine.go
    note for Content "defined: search/search_engine.go:308-318"
    class ContextLines {
        +ContextLines(string, map[int]bool, int, int, int): []api.ContextLine
    }
    <<function>> ContextLines
    %% grepple:file ContextLines search/context.go
    note for ContextLines "defined: search/context.go:11-39"
    class DiffNavigationGraphs {
        +DiffNavigationGraphs(parser.NavigationGraph, parser.NavigationGraph): NavigationGraphDiff
    }
    <<function>> DiffNavigationGraphs
    %% grepple:file DiffNavigationGraphs search/navigation_diff.go
    note for DiffNavigationGraphs "defined: search/navigation_diff.go:39-50"
    class EnforcePageLimit {
        +EnforcePageLimit(*Params, api.SearchRequest)
    }
    <<function>> EnforcePageLimit
    %% grepple:file EnforcePageLimit search/search_params.go
    note for EnforcePageLimit "defined: search/search_params.go:106-113"
    class Files {
        +Files(Params, []string): tuple~[]FileMatch&#44;error~
    }
    <<function>> Files
    %% grepple:file Files search/search_engine.go
    note for Files "defined: search/search_engine.go:190-227"
    class FilterNavigationGraph {
        +FilterNavigationGraph(parser.NavigationGraph, NavigationGraphFilter): tuple~parser.NavigationGraph&#44;error~
    }
    <<function>> FilterNavigationGraph
    %% grepple:file FilterNavigationGraph search/navigation_filter.go
    note for FilterNavigationGraph "defined: search/navigation_filter.go:20-38"
    class ListFilePaths {
        +ListFilePaths(Params, []string): tuple~[]string&#44;error~
    }
    <<function>> ListFilePaths
    %% grepple:file ListFilePaths search/search_engine.go
    note for ListFilePaths "defined: search/search_engine.go:389-391"
    class ListFilePathsContext {
        +ListFilePathsContext(context.Context, Params, []string): tuple~[]string&#44;error~
    }
    <<function>> ListFilePathsContext
    %% grepple:file ListFilePathsContext search/search_engine.go
    note for ListFilePathsContext "defined: search/search_engine.go:394-412"
    class NewRepoFilter {
        +NewRepoFilter([]string, []string): *RepoFilter
    }
    <<function>> NewRepoFilter
    %% grepple:file NewRepoFilter search/search_engine.go
    note for NewRepoFilter "defined: search/search_engine.go:136-138"
    class NormalizeNavigationGraphFilter {
        +NormalizeNavigationGraphFilter(NavigationGraphFilter): tuple~NavigationGraphFilter&#44;error~
    }
    <<function>> NormalizeNavigationGraphFilter
    %% grepple:file NormalizeNavigationGraphFilter search/navigation_filter.go
    note for NormalizeNavigationGraphFilter "defined: search/navigation_filter.go:41-55"
    class PathMatchesGlobs {
        +PathMatchesGlobs(string, []string): bool
    }
    <<function>> PathMatchesGlobs
    %% grepple:file PathMatchesGlobs search/search_glob.go
    note for PathMatchesGlobs "defined: search/search_glob.go:523-525"
    class QueryNavigationGraph {
        +QueryNavigationGraph(parser.NavigationGraph, []string, NavigationQueryDirection, int): tuple~parser.NavigationGraph&#44;error~
    }
    <<function>> QueryNavigationGraph
    %% grepple:file QueryNavigationGraph search/navigation_query.go
    note for QueryNavigationGraph "defined: search/navigation_query.go:28-47"
    class RepoID {
        +RepoID(string): string
    }
    <<function>> RepoID
    %% grepple:file RepoID search/search_engine.go
    note for RepoID "defined: search/search_engine.go:81-90"
    class RepoMatches {
        +RepoMatches(string, []string): bool
    }
    <<function>> RepoMatches
    %% grepple:file RepoMatches search/search_params.go
    note for RepoMatches "defined: search/search_params.go:118"
    class RepoMatchesAny {
        +RepoMatchesAny(string, []string): bool
    }
    <<function>> RepoMatchesAny
    %% grepple:file RepoMatchesAny search/search_params.go
    note for RepoMatchesAny "defined: search/search_params.go:121"
    class ResolveRequest {
        +ResolveRequest(api.SearchRequest): tuple~Params&#44;error~
    }
    <<function>> ResolveRequest
    %% grepple:file ResolveRequest search/search_params.go
    note for ResolveRequest "defined: search/search_params.go:11-40"
    class SortRepoCounts {
        +SortRepoCounts([]api.RepoCount)
    }
    <<function>> SortRepoCounts
    %% grepple:file SortRepoCounts search/search_engine.go
    note for SortRepoCounts "defined: search/search_engine.go:518-528"
    class SplitLines {
        +SplitLines(string): []string
    }
    <<function>> SplitLines
    %% grepple:file SplitLines search/search_engine.go
    note for SplitLines "defined: search/search_engine.go:24-33"
    class ToResult {
        +ToResult(FileMatch, []parser.Segment, int, int, int): api.FileResult
    }
    <<function>> ToResult
    %% grepple:file ToResult search/result.go
    note for ToResult "defined: search/result.go:13-41"
    class WorkerCount {
        +WorkerCount(): int
    }
    <<function>> WorkerCount
    %% grepple:file WorkerCount search/workers.go
    note for WorkerCount "defined: search/workers.go:19-34"
    AggregateRepoCounts "1" ..> "*" FileMatch : parameter 1
    AnalyzeDirectoryResponsibilities "1" ..> "*" ResponsibilityBoundaryCandidate : result 1
    AnalyzeResponsibilities "1" ..> "1" ResponsibilityReport : result 1
    At "1" ..> "1" FileMatch : result 1
    At "1" ..> "1" Params : parameter 1
    BuildResults "1" ..> "*" FileMatch : parameter 1
    Content "1" ..> "1" FileMatch : result 1
    Content "1" ..> "1" Params : parameter 1
    DiffNavigationGraphs "1" ..> "1" NavigationGraphDiff : result 1
    EnforcePageLimit "1" ..> "1" Params : parameter 1
    FileMatch "1" --> "*" RelatedPoint : field Related
    Files "1" ..> "*" FileMatch : result 1
    Files "1" ..> "1" Params : parameter 1
    FilterNavigationGraph "1" ..> "1" NavigationGraphFilter : parameter 2
    ListFilePaths "1" ..> "1" Params : parameter 1
    ListFilePathsContext "1" ..> "1" Params : parameter 2
    NavigationGraphDiff "1" --> "*" NavigationCallDelta : field ChangedCalls
    NavigationGraphDiff "1" --> "*" NavigationDeclarationDelta : field ChangedDeclarations
    NavigationGraphDiff "1" --> "*" NavigationDeclarationDelta : field MovedDeclarations
    NewRepoFilter "1" ..> "1" RepoFilter : result 1
    NormalizeNavigationGraphFilter "1" ..> "1" NavigationGraphFilter : parameter 1
    NormalizeNavigationGraphFilter "1" ..> "1" NavigationGraphFilter : result 1
    QueryNavigationGraph "1" ..> "1" NavigationQueryDirection : parameter 3
    RelatedPoint "1" --> "1" RelatedPreview : field Preview
    RelatedPreview "1" --> "*" RelatedPoint : field Related
    RepoFilter "1" --> "*" repoPattern : field exclude
    RepoFilter "1" --> "*" repoPattern : field include
    ResolveRequest "1" ..> "1" Params : result 1
    ResponsibilityBoundaryCandidate "1" --> "1" ResponsibilityBreadth : field Consumers
    ResponsibilityBoundaryCandidate "1" --> "*" ResponsibilityConsumer : field ConsumerDetails
    ResponsibilityBoundaryCandidate "1" --> "*" ResponsibilityPattern : field CallableCoUsage
    ResponsibilityBoundaryCandidate "1" --> "*" ResponsibilityPattern : field MemberCallCombinations
    ResponsibilityBoundaryCandidate "1" --> "*" ResponsibilityPattern : field OrderedSequences
    ResponsibilityBoundaryCandidate "1" --> "1" ResponsibilitySurface : field ExternalCallableSurface
    ResponsibilityPattern "1" --> "*" ResponsibilityConsumer : field Consumers
    ResponsibilityReport "1" --> "1" ResponsibilityBreadth : field Consumers
    ResponsibilityReport "1" --> "*" ResponsibilityConsumer : field ConsumerDetails
    ResponsibilityReport "1" --> "*" ResponsibilityPattern : field MemberMethodCombinations
    ResponsibilityReport "1" --> "*" ResponsibilityPattern : field MethodCoUsage
    ResponsibilityReport "1" --> "*" ResponsibilityPattern : field OrderedSequences
    ResponsibilityReport "1" --> "1" ResponsibilitySurface : field ExternalMethodSurface
    ToResult "1" ..> "1" FileMatch : parameter 1
    candidateCollector "1" --> "1" gitignoreCache : field ignoreCache
    candidateScan "1" ..> "*" FileMatch : method scanAll result 1
    candidateScan "1" ..> "*" FileMatch : method scanWindowed result 1
    candidateScan "1" --> "1" Params : field p
    candidateScan "1" --> "1" RepoFilter : field repoFilter
    navigationCaller "1" --> "1" navigationCall : field call
    navigationCaller "1" --> "1" navigationDeclaration : field declaration
    navigationCandidateResolution "1" --> "*" navigationDeclaration : field candidates
    navigationDeclaration "1" --> "1" RelatedPoint : field point
    navigationIndex "1" --> "*" navigationCall : field calls
    navigationIndex "1" ..> "1" navigationCall : method inferCallReturnReceiver parameter 1
    navigationIndex "1" ..> "*" navigationCall : method navigationCallsByID result 1
    navigationIndex "1" ..> "*" navigationCall : method resolveGraphCall parameter 2
    navigationIndex "1" ..> "1" navigationCall : method resolveReturnFactory parameter 1
    navigationIndex "1" --> "*" navigationCaller : field callers
    navigationIndex "1" --> "*" navigationDeclaration : field byFile
    navigationIndex "1" --> "*" navigationDeclaration : field byLocation
    navigationIndex "1" --> "*" navigationDeclaration : field declarations
    navigationIndex "1" ..> "*" navigationDeclaration : method addCalls parameter 2
    navigationIndex "1" ..> "*" navigationDeclaration : method addDeclarations result 1
    navigationIndex "1" ..> "*" navigationDeclaration : method navigationDeclarationsByID result 1
    navigationIndex "1" ..> "*" navigationDeclaration : method resolveGraphCall parameter 3
    navigationIndex "1" ..> "1" navigationDeclaration : method resolveReturnFactory result 1
    responsibilityAnalyzer "1" ..> "1" ResponsibilityConsumer : method addResponsibilityCaller result 1
    responsibilityAnalyzer "1" ..> "1" ResponsibilityReport : method report result 1
    responsibilityAnalyzer "1" --> "*" responsibilityInteraction : field interactionsByCaller
    responsibilityAnalyzer "1" ..> "*" responsibilityInteraction : method addResponsibilityCaller parameter 2
    responsibilityAnalyzer "1" ..> "1" responsibilityPatternGroups : method addResponsibilityCaller parameter 3
    responsibilityOwnerAnalysis "1" --> "*" responsibilityInteraction : field interactions
    responsibilityPatternGroup "1" --> "*" ResponsibilityConsumer : field consumers
    responsibilityPatternGroups "1" --> "*" responsibilityPatternGroup : field combinations
    responsibilityPatternGroups "1" --> "*" responsibilityPatternGroup : field methodSets
    responsibilityPatternGroups "1" --> "*" responsibilityPatternGroup : field sequences
