classDiagram
    %% grepple:complete-package grepple/internal/command
    %% grepple:package-default grepple/internal/command
    %% grepple:language-default go
    %% grepple:exact-default
    class Run {
        +Run([]string, func&#40;[]string&#41;error)
    }
    <<function>> Run
    %% grepple:file Run internal/command/command.go
