package metrics

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"reflect"
)

const maxReportBytes = 64 << 20

// ReadReport reads one bounded, canonical JSON report previously generated by Grepple.
func ReadReport(path string) (Report, error) {
	file, err := os.Open(path)
	if err != nil {
		return Report{}, err
	}
	defer file.Close()
	content, err := io.ReadAll(io.LimitReader(file, maxReportBytes+1))
	if err != nil {
		return Report{}, fmt.Errorf("read metrics report: %w", err)
	}
	if len(content) > maxReportBytes {
		return Report{}, fmt.Errorf("metrics report exceeds %d bytes", maxReportBytes)
	}
	var report Report
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&report); err != nil {
		return Report{}, fmt.Errorf("decode metrics report: %w", err)
	}
	if err := rejectTrailingReportJSON(decoder); err != nil {
		return Report{}, err
	}
	if report.Schema != "grepple-agent-report-v1" {
		return Report{}, fmt.Errorf("unsupported metrics report schema %q", report.Schema)
	}
	canonical := BuildReport(report.Runs)
	if !reflect.DeepEqual(report, canonical) {
		return Report{}, fmt.Errorf("metrics report is not a canonical generated report")
	}
	return report, nil
}

func rejectTrailingReportJSON(decoder *json.Decoder) error {
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return fmt.Errorf("decode metrics report: trailing JSON value")
		}
		return fmt.Errorf("decode metrics report: %w", err)
	}
	return nil
}
